# Site settings
title: IT Software
email: 2024932008@g.shingu.ac.kr
url: "https://2024932008.github.io" # the base hostname & protocol for your site
description: "for lecture"
keywords: "itsoftware"
skills: "어쩌구 저쩌구"
meta_author: 2024932008kgy